#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SERVER_ENV="$ROOT_DIR/server/.env.local"
SEED_SRC="$ROOT_DIR/server/data/seed.json"
SEED_DST="$ROOT_DIR/server/data/db.json"

echo "=== BestNote local setup helper ==="

read -p "Jameica install path (leave empty to skip) [ /opt/jameica ]: " JAMEICA_PATH
JAMEICA_PATH=${JAMEICA_PATH:-/opt/jameica}

read -p "Nextcloud WebDAV URL (e.g. https://nextcloud.example/remote.php/dav/files/username/) [skip]: " NEXTCLOUD_URL
if [ -n "$NEXTCLOUD_URL" ]; then
  read -p "Nextcloud username: " NEXTCLOUD_USER
  read -s -p "Nextcloud password: " NEXTCLOUD_PASS
  echo
fi

echo "Writing configuration to $SERVER_ENV"
mkdir -p "$(dirname "$SERVER_ENV")"
cat > "$SERVER_ENV" <<EOF
# Generated by scripts/setup_local_env.sh
JAMEICA_PATH="$JAMEICA_PATH"
NEXTCLOUD_URL="${NEXTCLOUD_URL:-}"
NEXTCLOUD_USER="${NEXTCLOUD_USER:-}"
NEXTCLOUD_PASS="${NEXTCLOUD_PASS:-}"
EOF

echo "Seeding example database"
mkdir -p "$(dirname "$SEED_DST")"
if [ -f "$SEED_SRC" ]; then
  cp "$SEED_SRC" "$SEED_DST"
  echo "Seed DB copied to $SEED_DST"
else
  echo "Seed source $SEED_SRC not found — skipping copy"
fi

echo "Optional: Import jVerein/OpenVerein CSV file"
read -p "Path to CSV file to import (or leave empty to skip): " IMPORT_FILE
if [ -n "$IMPORT_FILE" ]; then
  if command -v node >/dev/null 2>&1; then
    node "$ROOT_DIR/scripts/import_jverein.js" "$IMPORT_FILE" "$ROOT_DIR/server/data/imported_members.json"
    echo "Imported file saved to server/data/imported_members.json"
  else
    echo "Node.js not found — cannot run import helper. Install Node.js and re-run."
  fi
fi

echo "Done. Next steps:"
echo " - Start the frontend: npm run dev"
echo " - Start the server (if applicable) in server/: refer to server/README.md"
echo " - If you configured Nextcloud, verify the WebDAV connection from the app settings"
